name: Random acts of discovery
favicon: null
layout_spectrum: 0
typography_spectrum: 0.00016306829638779163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6aa2db'
    - '#2e5f87'
    - '#c16153'
    - '#080808'
  brandStrength: 0.948645340045914
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
